{
    'name': 'Booking room',
    'version': '1.0',
    'application': True,
    'installable': True,
    'depends': ['base', 'mail', 'hr'],
    'data': [
             'security/groups.xml',
             'security/ir.model.access.csv',
             'views/room_views.xml',
             'views/room_booking_views.xml',
             'views/room_equip_views.xml',
             'views/equipment_brands.xml',
             'views/equipment_color.xml',
             'views/room_booking_menu.xml',
             'data/email_template.xml',
             'data/cancel_email_template.xml',
             # 'reports/report.xml',
             ],
    'license': 'GPL-3',
}
